management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health,info"
  info:
    git:
      enabled: true
    env:
      enabled: true
spring:
  application:
    name: actuator-info-app
#info:
#  application:
#    name: ${spring.application.name}
#    description: Very cool Spring Boot application
#    version: '@project.version@'
#    spring-cloud-version: '@spring-cloud.version@'
#    spring-boot-version: '@project.parent.version@'